### ISSUE TITLE
Commit messages

### ISSUE THREAD

**Issue by ppassmannpriv** [patplue/web_components#3]
Make an effort to write meaningful commit messages. "First", "stuff", "asdf", "init" are going to annoy you in 3-4 weeks, when you haven't looked at this in a while. Trust me, I've been there.

**Comment by patplue** [comment]
i hope i did better this time lol

**Comment by ppassmannpriv** [comment]
Maybe yeah - it is better deffo. Think about a structure you stick to. I have previously used "tags" in brackets in my messages like:
```
[FIX] Fixed issue with icon glitching on hover

Here should follow a details description on what you changed and how it might have effects and stuff
```
Other Tags could be [FEATURE] or [UPDATE] or [MAINTENANCE] or when you do client stuff and have ticket ids [#1234]
